[package]
name = "zetanom"
version = "0.1.0"
edition = "2024"
description = "A diet-tracking app."
homepage = "https://github.com/eudoxia0/zetanom"
repository = "https://github.com/eudoxia0/zetanom"
license = "Apache-2.0"
categories = ["command-line-utilities"]

[dependencies]
axum = "0.8.6"
clap = { version = "4.5.51", features = ["derive"] }
tokio = { version = "1.48.0", features = ["rt-multi-thread"] }
