[package]
name = "www"
version = "0.0.0"
edition.workspace = true
license.workspace = true

[dependencies]
db.workspace = true
error.workspace = true
axum.workspace = true
tokio.workspace = true
maud.workspace = true
