[package]
name = "www"
version = "0.0.0"
edition.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
chrono.workspace = true
db.workspace = true
error.workspace = true
maud = "0.27.0"
serde = { version = "1.0.228", features = ["derive"] }
tokio.workspace = true
