[package]
name = "db"
version = "0.0.0"
edition.workspace = true
license.workspace = true

[dependencies]
error.workspace = true
rusqlite.workspace = true
shared.workspace = true
chrono.workspace = true
