[package]
name = "db"
version = "0.0.0"
edition.workspace = true
license.workspace = true

[dependencies]
error.workspace = true
axum.workspace = true
tokio.workspace = true
maud.workspace = true
rusqlite.workspace = true
